### ISSUE TITLE
Data Model Documentation

### ISSUE THREAD

**Issue by Kirei-Nan** [CSCI-GA-2820-FA24-001/orders#116]
As an API consumer
I need clear documentation of API data models
So that I understand the exact format of requests and responses

Details and Assumptions
* Need Swagger models for Order and Item
* Models should include all fields and validations
* Need to document relationships between models
* Should include example values
* Must document all possible status values

Acceptance Criteria

Given the Swagger documentation
When I view the model definitions
Then I should see complete Order and Item models
And all fields should be properly typed
And required fields should be marked
And example values should be provided

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Update routes.py to include Swagger documentation for the Order and Item models using Flask-RESTx. This will provide clear API data model documentation as requested in the GitHub issue.

You can review changes in this commit: https://github.com/lkilu6456546/CSCI-GA-2820-FA24-001-orders-117/commit/13433476439462cedb154e28d2a749e75fa8d7b9.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
